version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=cliknews
    - MYSQL_DATABASE=cliknews
    - MYSQL_USER=cliknews
    - MYSQL_PASSWORD=cliknews
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  cliknews:
    build: .
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - cliknews-files:/app/server/files

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  cliknews-files:

