version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=cliker
    - MYSQL_DATABASE=cliker
    - MYSQL_USER=cliker
    - MYSQL_PASSWORD=cliker
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  cliker:
    build:
      context: .
      dockerfile: Dockerfile-Develop
    ports:
    - "3100:3000"
    - "3103:3003"
    - "3104:3004"
    volumes:
    - ./:/app

  landing:
    build:
      context: ./landing
      args:
        NEXT_PUBLIC_APP_URL: http://localhost:3100
    environment:
    - NEXT_PUBLIC_APP_URL=http://localhost:3100
    - PLANS_API_URL=http://cliker:3004/api/public/plans
    ports:
    - "3105:3000"

volumes:
  mysql-data:
  redis-data:
  mongo-data: