version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=cliker
    - MYSQL_DATABASE=cliker
    - MYSQL_USER=cliker
    - MYSQL_PASSWORD=cliker
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  cliker:
    build: .
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - cliker-files:/app/server/files

  landing:
    build:
      context: ./landing
    environment:
    - NEXT_PUBLIC_APP_URL=http://localhost:3000
    - PLANS_API_URL=http://cliker:3004/api/public/plans
    ports:
    - "3005:3000"

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  cliker-files:

